charging:
  # --- federate parameters ---
  name: charging
  routing_key: charging
  queue_name: charging_queue
  adapter: ChargingAdapter
  output_type: ChargingOutput
  timestep_length: 60.0

  # --- model parameters ---
  charging_rate: 1.0