transportation:
  # --- federate parameters ---
  name: transportation
  routing_key: transportation
  queue_name: transportation_queue
  adapter: TransportationAdapter
  output_type: TransportationOutput
  timestep_length: 1.0

  # --- model parameters ---
  sumo_config: /Users/maltegaber/Downloads/Transportation Model/main.sumocfg